### ISSUE TITLE
Add SublimeGtags to Package Control community packages

### ISSUE THREAD

**Issue by pitkali** [koko1000ban/SublimeGtags#1]
It would be useful to add SublimeGtags to list of community packages in Package Control (see http://wbond.net/sublime_packages/package_control). The benefits would include:
- Easy installation
- Automatic updates
- Ability to automatically install on another installation of Sublime Text 2 upon synchronisation of Package Control settings stored in User directory

**Comment by koko1000ban** [comment]
Thank you for your suggestion :) i will add my plugin to list of community packages.

**Comment by koko1000ban** [comment]
merged https://github.com/wbond/package_control_channel/pull/331
thanks!

**Comment by pitkali** [comment]
Splendid! :)
