### ISSUE TITLE
Enable path shortening when searching for references

### ISSUE THREAD

**Issue by pitkali** [koko1000ban/SublimeGtags#2]
When searching for all references of a symbol in a project with long paths these paths become hardly readable. (Especially if you use 2-column layout so that the view of the file is quite narrow, say 100 characters.)

It would help if there was an option to remove prefixes of these paths, and, for example, instead of showing absolute paths, show paths relative to the located tags file.

**Comment by refaim** [comment]
Implemented in b2dd45f9a0775b4a891a3c9b1ddd5b3c00e37a22, please close.

**Comment by pitkali** [comment]
Thanks! You're my hero, even if you broke the commands I use most on Mac ;) (but that is fixed by your next pull request).
